### ISSUE TITLE
README in each task folder

### ISSUE THREAD

**Issue by shippy** [YaleDecisionNeuro/PsychTaskFramework#120]
Describe what the task is for, and ideally, include screenshots.

**Comment by shippy** [comment]
Gifs of practice (uncut) added in 5c286fef68578d3c427cb98c71d4999de5b6f570.

**Comment by shippy** [comment]
Level of detail: less than you'd require in the Methods section, as that can easily be added later. Each task gets a:

- [ ] High-level task description
- [ ] Description of user and subject interaction (keys, trial duration, session duration)
- [ ] Number of trials and values/probabilities involved

**Comment by shippy** [comment]
@skim725, any chance that I could get your help on this, please?

**Comment by skim725** [comment]
Sure! This is for SODM, MDM, UVRA..? Let's discuss tomorrow?

**Comment by shippy** [comment]
Yup! SODM, UVRA, MDM, RA, HLFF in descending order of priority.

**Comment by shippy** [comment]
It seems that I've either recorded the MDM practice wrong, or to set up wrong – I can't see any medical symbols coming up. So, we'll need to rerecord it.

**Comment by shippy** [comment]
This exists on Sarah's branches, which were in PRs #134, #135, #136, and #137. IIRC we closed these because they introduced a lot of commits separately and I wanted Sarah to collapse them into fewer commits and one PR. Next order of business: cherrypick, then PR.

**Comment by shippy** [comment]
Oh, they're actually branches in this repository! Nevermind then - re-opening and collapsing it is!
