### ISSUE TITLE
Task: Risk-only high-/low-fat foods (HLFF)

### ISSUE THREAD

**Issue by shippy** [YaleDecisionNeuro/PsychTaskFramework#71]
The task that @sch64 wants to run has (at least) the following specs:

* [x] No ambiguity trials
* [x] Three kinds of blocks: monetary, low-fat foods, high-fat foods

Sarah will add more specs (number of blocks and trials, ...) at a later time.

**Comment by shippy** [comment]
Details:
* Money domain:
  * 4 outcome levels: $5 (reference), $8, $12, $25
  * 4 repeats for each trial: 9 x 4 = 36 trials + 2 reference trials = 38 trials by 2 blocks = 19 trials     per block
* High fat domain (likely Nabisco mini Oreos)
  * 4 outcome levels: 4 cookies (reference), 6, 9, 18
  * 4 repeats for each trial + 2 reference trials: 38 trials total for 2 blocks = 19 trials per block
* Low fat domain (likely Snyder's unsalted mini pretzels)
  * 4 outcome levels: 10 pretzels (reference), 15, 20, 30
  * 4 repeats for each trial + 2 reference trials: 38 trials total, 19 trials per block

Overall:
  - 3 different risk situations: reference vs. 25% win, 50% win, 75% win
  - 6 blocks (two for each domain)
  - 19 trials per block, all of the same domain
  - 2 money blocks first, then randomized order of high fat and low fat blocks

**Comment by shippy** [comment]
![4 oreos](https://git.yale.edu/storage/user/1373/files/069d2e6c-057e-11e7-83fd-8783e411a163)
![6 oreos](https://git.yale.edu/storage/user/1373/files/07a8e170-057e-11e7-8e67-94817bef80c0)
![9 oreos](https://git.yale.edu/storage/user/1373/files/0905a4c2-057e-11e7-90a4-ad3add6d8027)
![18 oreos](https://git.yale.edu/storage/user/1373/files/0a7db0f6-057e-11e7-8682-2b9e35305c25)

**Comment by shippy** [comment]
![10 pretzels](https://git.yale.edu/storage/user/1373/files/1271515a-057e-11e7-9033-bec143a95e5f)
![15 pretzels](https://git.yale.edu/storage/user/1373/files/13980d8a-057e-11e7-80d6-f7ce3f5bf2ab)
![20 pretzels](https://git.yale.edu/storage/user/1373/files/15816bdc-057e-11e7-852c-b28ed3389dca)
![30 pretzels](https://git.yale.edu/storage/user/1373/files/181564c0-057e-11e7-93bb-871d30deeb7e)

**Comment by shippy** [comment]
@sch64, I assume you want probably want smaller image display? Here's a screenshot of what images this size look like now:

![image](https://git.yale.edu/storage/user/436/files/b7f48550-0800-11e7-85ae-cdddc7baca82)

**Comment by shippy** [comment]
Partial implementation has been merged into `master` as of 4ecc1757729eaa767e73c615f9e153ada126675b. Remaining:
* [ ] Right-size the images
* [ ] Create block config for the high-fat condition
* [ ] Create block config for the monetary condition
* [ ] Generate blocks and double-check with Sarah that they're correct

**Comment by shippy** [comment]
@sch64: Check out the branch `71_HLFF` and try running `HLFF(3)`. I know that I don't have the right number of repeats right now, but in all other aspects, does it look the way you think it ought to?

**Comment by sch64** [comment]
@shippy sorry for the late response-- it looks great, and let me know if there is anything further I can do to help!

**Comment by shippy** [comment]
Reopening until the lowest value trials are only repeated once (see #107 and `MDM` task; alternatively, until #109 is implemented.).
